{{- range .Values.ComputeInstances }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    demo: google-next-2020
spec:
  description: {{ .description | quote }}
  machineType: n1-standard-1
  tags:
    - icmp
  zone: us-central1-a
  bootDisk:
    initializeParams:
      size: 20
      type: pd-standard
      sourceImageRef:
        external: debian-cloud/debian-9
  networkInterface:
    - subnetworkRef:
        name: "next-gitops-demo-1-subnet-1"
  scheduling:
    preemptible: true
---
{{- end }}
