{{- range .Values.ComputeNetworks }}
{{- $NetworkName := .name -}}
{{- range .ComputeSubNetworks }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ print $NetworkName "-" .name }}
  labels:
    demo: google-next-2020
spec:
  ipCidrRange: {{ .ipCidrRange }}
  region: {{ .region }}
  networkRef:
    name: {{ $NetworkName }}
---
{{- end }}
{{- end }}
