{{- range .Values.ComputeNetworks }}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  namespace: {{ $.Values.namespace }}
  name: {{ .name }}
  labels:
    demo: google-next-2020
spec:
  autoCreateSubnetworks: false
  routingMode: {{ .routingMode }}
  description: {{ .description | quote }}
---
{{- end }}
