kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eunomia-runner
  namespace: "gcp-gitops-demo"
subjects: 
- kind: ServiceAccount
  name: eunomia-runner
  namespace: "gcp-gitops-demo"
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io  
---
# Service accounts for app namespaces
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eunomia-runner
  namespace: "gcp-gitops-demo"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eunomia-operator-cluster-admin-gcp-gcp-gitops-demo
  namespace: "gcp-gitops-demo"
subjects:
- kind: ServiceAccount
  name: eunomia-runner
  namespace: "gcp-gitops-demo"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
