namespace: "next-gitops-demo"
ComputeNetworks:
  - name: "gitops-next-demo-1"
    description: "A network for our GitOps Demo @ Google NEXT 2020"
    routingMode: REGIONAL
    ComputeSubNetworks:
      - name: "subnet1"
        region: us-central1
        ipCidrRange: 10.1.1.0/24
      - name: "subnet2"
        region: us-central1
        ipCidrRange: 10.1.2.0/24
