namespace: "next-gitops-demo"
ComputeNetworks:
  - name: "next-gitops-demo-1"
    description: "A network for our GitOps Demo @ Google NEXT 2020"
    routingMode: REGIONAL
    ComputeSubNetworks:
      - name: "subnet-1"
        region: us-central1
        ipCidrRange: 10.1.1.0/24
      - name: "subnet-2"
        region: us-central1
        ipCidrRange: 10.1.2.0/24
    ComputeFirewall:
      - name: "default-deny"
        priority: 65535
        direction: INGRESS
        description: "Default Deny"
        sourceRanges:
          - "0.0.0.0/0"
        deny:
          - protocol: "icmp"
          - protocol: "tcp"
          - protocol: "udp"
      - name: "allow-icmp"
        priority: 900
        direction: INGRESS
        description: "Allow ICMP"
        targetTags:
          - "icmp"
        allow:
          - protocol: "icmp"
        sourceRanges:
          - "10.0.0.0/8"
      - name: "allow-ssh"
        priority: 900
        direction: INGRESS
        description: "Allow SSH from Google's Jump Hosts"
        targetTags:
          - "ssh"
        sourceRanges:
          - "35.235.240.0/20"
        allow:
          - protocol: "tcp"
            ports: ["22"]
